[rtl_sdr]
sample_rate = 1024000
center_freq_mhz = 434.900
gain_mode = 0
fm_mode = narrow    ; am, wide or narrow

[audio]
audio_rate = 48000
mp3_bitrate = 128
mp3_quality = 2
audio_buffer_seconds = 2

[audio_filters]
lowcut_enabled = true    ; true or false
lowcut_freq = 500.0      ; in Hz, frequencies below this will be attenuated
lowcut_order = 4         ; filter order (higher = steeper cutoff, but more CPU)

[squelch]
enabled = true    ; true or false
threshold = -25.0  ; in dB, signals below this will be muted
hold_time = 500    ; in milliseconds, how long to keep squelch open after signal drops

[icecast]
host = kapsi.fi
port = 62780
mount = /dev.mp3
station_title=Streaming airband
password = hackme
user = source
protocol = http    ; only http is supported for now
format = mp3
reconnect_attempts = 5
reconnect_delay_ms = 2000 

[scanner]
scan = true ;false
step_delay = 500 ; ms

[scanlist]
;ch0 = 434.550,NFM,DMR Tesoma
;ch1 = 434.525,NFM,DMR Hervanta
ch2 = 144.800,NFM,APRS
ch3 = 434.850,NFM,OH3NE 70cm
ch4 = 403.000,NFM,Sonde
